# Synthetic, model-free check of the common source collector; no compiler, Git or network needed.
cmake_minimum_required(VERSION 3.22)
get_filename_component(collector "${CMAKE_CURRENT_LIST_DIR}/../../packaging/cmake/sources.cmake" ABSOLUTE)
if(NOT DEFINED WT_TEST_DIR OR WT_TEST_DIR STREQUAL "")
    message(FATAL_ERROR "Pass a fresh WT_TEST_DIR")
endif()
get_filename_component(work "${WT_TEST_DIR}" ABSOLUTE)
if(EXISTS "${work}")
    message(FATAL_ERROR "Use a fresh WT_TEST_DIR: ${work}")
endif()
set(source "${work}/source with spaces")
set(build "${work}/build with spaces")
set(bundle "${work}/bundle with spaces")
set(project_files CMakeLists.txt CMakePresets.json vcpkg.json .gitattributes LICENSE
    cmake/fixture.cmake src/main.cpp tests/.hidden packaging/fixture.sh)
foreach(path IN LISTS project_files)
    file(WRITE "${source}/${path}" "fixture ${path}\n")
endforeach()
foreach(path IN ITEMS README.md .git/config .build/artifact transcripts/private.txt)
    file(WRITE "${source}/${path}" "must not be packaged\n")
endforeach()
set(dep_dirs whisper cli11 nlohmann_json)
set(dep_archives whisper.cpp-abc123 CLI11-2.5.0 nlohmann-json-3.12.0)
set(dep_notices LICENSE LICENSE LICENSE.MIT)
set(dep_licenses whisper.cpp-MIT CLI11-BSD nlohmann-json-MIT)
foreach(index RANGE 0 2)
    list(GET dep_dirs ${index} dir)
    list(GET dep_notices ${index} notice)
    file(WRITE "${build}/_deps/${dir}-src/${notice}" "${dir} license\n")
    file(WRITE "${build}/_deps/${dir}-src/include/fixture.h" "${dir} header\n")
    file(WRITE "${build}/_deps/${dir}-src/.hidden" "hidden upstream source\n")
endforeach()
set(metadata "WT_PACKAGE_VERSION=0.5.0-dev+gabc123\nWT_WHISPER_REVISION=abc123\nWT_CLI11_VERSION=2.5.0\nWT_JSON_VERSION=3.12.0\n")
function(collect expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DWT_SOURCE_DIR=${source}" "-DWT_BUILD_DIR=${build}"
        "-DWT_BUNDLE_DIR=${bundle}" -P "${collector}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(expected STREQUAL "success")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Collector failed: ${out}${err}")
        endif()
    elseif(result EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection '${expected}', got ${result}: ${out}${err}")
    endif()
endfunction()
function(compare_file actual expected)
    file(SHA256 "${actual}" actual_hash)
    file(SHA256 "${expected}" expected_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Source bytes differ: ${actual}")
    endif()
endfunction()
function(check_archive archive original expected)
    set(unpack "${work}/unpack/${archive}")
    file(REMOVE_RECURSE "${unpack}")
    file(MAKE_DIRECTORY "${unpack}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xzf "${bundle}/sources/${archive}.tar.gz"
        WORKING_DIRECTORY "${unpack}" COMMAND_ERROR_IS_FATAL ANY)
    file(GLOB_RECURSE actual LIST_DIRECTORIES false RELATIVE "${unpack}" "${unpack}/*")
    list(SORT actual)
    list(SORT expected)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Archive contents differ: ${archive}: ${actual} != ${expected}")
    endif()
    foreach(path IN LISTS expected)
        compare_file("${unpack}/${path}" "${original}/${path}")
    endforeach()
endfunction()
foreach(newline IN ITEMS LF CRLF)
    set(contents "${metadata}")
    if(newline STREQUAL "CRLF")
        string(REPLACE "\n" "\r\n" contents "${contents}")
    endif()
    file(WRITE "${build}/generated/package.env" "${contents}")
    collect(success)
    check_archive(whisper-transcribator-0.5.0-dev+gabc123 "${source}" "${project_files}")
    compare_file("${bundle}/licenses/whisper-transcribator-MIT.txt" "${source}/LICENSE")
    foreach(index RANGE 0 2)
        list(GET dep_dirs ${index} dir)
        list(GET dep_archives ${index} archive)
        list(GET dep_notices ${index} notice)
        list(GET dep_licenses ${index} license)
        check_archive("${archive}" "${build}/_deps/${dir}-src" "${notice};include/fixture.h;.hidden")
        compare_file("${bundle}/licenses/${license}.txt" "${build}/_deps/${dir}-src/${notice}")
    endforeach()
endforeach()
file(WRITE "${build}/generated/package.env" "${metadata}WT_PACKAGE_VERSION=duplicate\n")
collect("Duplicate package metadata")
file(WRITE "${build}/generated/package.env" "WT_PACKAGE_VERSION=../escape\n")
collect("Missing or unsafe package metadata")
file(WRITE "${build}/generated/package.env" "WT_PACKAGE_VERSION=valid\n")
collect("Missing or unsafe package metadata: WT_WHISPER_REVISION")
file(WRITE "${build}/generated/package.env" "malformed\n")
collect("Invalid package metadata")
file(WRITE "${build}/generated/package.env" "${metadata}")
file(REMOVE "${build}/_deps/cli11-src/LICENSE")
collect("Missing dependency notice")
file(REMOVE "${source}/.gitattributes")
collect("Missing project source")
file(REMOVE_RECURSE "${work}")
message(STATUS "Source archive and notice contracts passed")
