cmake_minimum_required(VERSION 3.22)
find_program(GIT git REQUIRED)
set(source "${WT_ROOT}/source")
set(build "${WT_ROOT}/build")
file(REMOVE_RECURSE "${WT_ROOT}")
file(MAKE_DIRECTORY "${source}/cmake" "${build}/generated")
file(COPY "${WT_SOURCE}/cmake/version.hpp.in" "${WT_SOURCE}/cmake/package.env.in" DESTINATION "${source}/cmake")
function(generate revision dirty)
  set(PROJECT_VERSION 0.4.0)
  set(WT_VERSION_SUFFIX -dev)
  if(ARGC GREATER 2)
    set(WT_VERSION_SUFFIX "${ARGV2}")
  endif()
  set(WT_SOURCE_REVISION "${revision}")
  set(WT_SOURCE_DIRTY "${dirty}")
  set(CMAKE_CURRENT_SOURCE_DIR "${source}")
  set(CMAKE_CURRENT_BINARY_DIR "${build}")
  configure_file("${WT_SOURCE}/cmake/build-version.cmake.in" "${build}/version.cmake" @ONLY)
endfunction()
function(check pattern)
  execute_process(COMMAND "${CMAKE_COMMAND}" -P "${build}/version.cmake" COMMAND_ERROR_IS_FATAL ANY)
  file(READ "${build}/generated/package.env" metadata)
  if(NOT metadata MATCHES "${pattern}")
    message(FATAL_ERROR "Version metadata does not match ${pattern}: ${metadata}")
  endif()
endfunction()
function(git)
  execute_process(COMMAND "${GIT}" ${ARGN} WORKING_DIRECTORY "${source}" COMMAND_ERROR_IS_FATAL ANY OUTPUT_QUIET)
endfunction()
generate("" "")
check("WT_PACKAGE_VERSION=0.4.0-dev\\+unknown.state-unknown")
generate("0123456789012345678901234567890123456789" false)
check("WT_PACKAGE_VERSION=0.4.0-dev\\+g012345678901\n")
git(init -q -b main)
git(config user.name "Version Test")
git(config user.email "test@users.noreply.github.com")
git(config commit.gpgsign false)
git(config core.hooksPath /dev/null)
git(add .)
git(commit -qm Initial)
generate("" "")
check("WT_SOURCE_DIRTY=false")
file(READ "${build}/generated/package.env" before)
file(APPEND "${source}/cmake/version.hpp.in" "\n// fixture edit\n")
check("\\.dirty\n")
git(add .)
git(commit -qm Second)
# Re-run the existing generated driver, without reconfiguring it after the commit.
check("WT_SOURCE_DIRTY=false")
file(READ "${build}/generated/package.env" after)
if(before STREQUAL after)
  message(FATAL_ERROR "Source revision did not refresh after committing")
endif()
file(REMOVE_RECURSE "${source}/.git")
check("WT_SOURCE_REVISION=unknown")
generate("0123456789012345678901234567890123456789" false "")
check("WT_PACKAGE_VERSION=0.4.0\n")
check("WT_SOURCE_REVISION=0123456789012345678901234567890123456789\n")
check("WT_SOURCE_DIRTY=false\n")
