add_executable(wt-audio-fixture support/tools/audio-fixture.cpp)
add_executable(wt-gpu-init-smoke smoke/gpu-init.cpp)
target_link_libraries(wt-gpu-init-smoke PRIVATE wt_engine)
wt_warnings(wt-gpu-init-smoke)
wt_manifest(wt-gpu-init-smoke)
target_include_directories(wt-audio-fixture PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(wt-audio-fixture PRIVATE wt_engine)
wt_warnings(wt-audio-fixture)
wt_manifest(wt-audio-fixture)
add_executable(wt-process-runner support/tools/process-runner.cpp)
target_link_libraries(wt-process-runner PRIVATE wt_test_support)
wt_warnings(wt-process-runner)
wt_manifest(wt-process-runner)
