wt_test(io unit unit/support/io.cpp)
wt_test(assertions unit unit/support/assertions.cpp)
wt_test(file-handle unit unit/platform/file-handle.cpp)
wt_test(formatting unit unit/transcript/rendering.cpp)
wt_test(jobs unit unit/transcript/jobs.cpp)
wt_test(model-cache unit unit/models/model-cache.cpp)
wt_test(boundaries unit unit/transcript/boundaries.cpp)
wt_test(cpu-limits unit unit/platform/cpu.cpp)
wt_test(devices unit unit/inference/devices.cpp)
wt_test(report unit unit/support/report.cpp)
wt_test(options unit unit/app/options.cpp)
wt_test(resampler unit unit/audio/resampler.cpp)
target_link_libraries(wt-resampler-tests PRIVATE wt_engine PkgConfig::AV)
wt_test(timeline unit unit/audio/timeline.cpp)
target_link_libraries(wt-timeline-tests PRIVATE wt_engine)
wt_test(decode-errors unit unit/audio/audio-recovery.cpp)
target_link_libraries(wt-decode-errors-tests PRIVATE wt_engine)
add_test(NAME unit/platform-boundary COMMAND "${CMAKE_COMMAND}" "-DWT_SOURCE=${CMAKE_SOURCE_DIR}"
  -P "${CMAKE_CURRENT_SOURCE_DIR}/unit/architecture/platform-boundary.cmake")
set_tests_properties(unit/platform-boundary PROPERTIES LABELS unit TIMEOUT 60)
add_test(NAME unit/module-boundary COMMAND "${CMAKE_COMMAND}" "-DWT_SOURCE=${CMAKE_SOURCE_DIR}"
  -P "${CMAKE_CURRENT_SOURCE_DIR}/unit/architecture/module-boundary.cmake")
set_tests_properties(unit/module-boundary PROPERTIES LABELS unit TIMEOUT 60)
