cmake_minimum_required(VERSION 3.22)

# Check project-owned adapters, not vendored sources or test doubles.
function(check_line source line result)
  set(error "")
  if(line MATCHES "^[ \t]*#[ \t]*include[ \t]*[<\"]([^>\"]+)[>\"]")
    set(header "${CMAKE_MATCH_1}")
    if((header MATCHES "^app/" OR header MATCHES "^CLI/") AND NOT source MATCHES "^app/")
      set(error "application dependency outside app")
    elseif(header MATCHES "^lib(avcodec|avformat|avutil|swresample)/" AND NOT source MATCHES "^audio/.*\\.cpp$")
      set(error "FFmpeg API outside audio implementation")
    elseif(header MATCHES "^(whisper|ggml[^/]*)\\.h$" AND NOT source MATCHES "^inference/.*\\.cpp$")
      set(error "inference API outside inference implementation")
    elseif(header STREQUAL "curl/curl.h" AND NOT source MATCHES "^models/.*\\.cpp$")
      set(error "curl API outside model transfer implementation")
    elseif(header MATCHES "^audio/detail/" AND NOT source MATCHES "^audio/.*\\.cpp$")
      set(error "private audio helper outside audio implementation")
    elseif(header MATCHES "^platform/win32/" AND
        NOT source MATCHES "^platform/(.*\\.cpp$|win32/.*\\.hpp$)")
      set(error "private Windows helper outside platform implementation")
    elseif(header STREQUAL "support/io.hpp")
      set(error "retired I/O umbrella instead of a responsibility-specific header")
    elseif(source MATCHES "^inference/" AND header STREQUAL "transcript/pipeline.hpp")
      set(error "inference depends on pipeline instead of pure window boundaries")
    elseif(source MATCHES "^transcript/boundaries\\.(cpp|hpp)$" AND
        (NOT header MATCHES "^transcript/(boundaries|types)\\.hpp$" AND header MATCHES "\\.hpp$"))
      set(error "window boundaries depend on services instead of value types")
    elseif(source MATCHES "^transcript/render/" AND
        header MATCHES "^(app|audio|inference|models|platform|support|transcript)/" AND
        NOT header MATCHES "^(support/json\\.hpp$|transcript/(types|options)\\.hpp$|transcript/render/)")
      set(error "renderer depends on application, storage or metadata construction")
    elseif(source MATCHES "^transcript/checkpoint/" AND header MATCHES "^transcript/(render/|publication\\.hpp$)")
      set(error "checkpoint depends on formatting instead of its render callback")
    elseif(header MATCHES "^transcript/checkpoint/detail/" AND
        NOT source MATCHES "^transcript/checkpoint/(.*\\.cpp$|detail/.*\\.hpp$)")
      set(error "private checkpoint helper outside checkpoint implementation")
    elseif(header MATCHES "^transcript/render/detail/" AND
        NOT source MATCHES "^transcript/render/(.*\\.cpp$|detail/.*\\.hpp$)")
      set(error "private rendering helper outside renderer implementation")
    elseif(source MATCHES "^models/(models|types)\\.hpp$" AND
        header MATCHES "^(models/download\\.hpp$|platform/)")
      set(error "model API leaks transport or native file access")
    endif()
  endif()
  if(NOT source MATCHES "^app/" AND line MATCHES "(^|[^A-Za-z0-9_])CliOptions([^A-Za-z0-9_]|$)")
    set(error "aggregate CLI settings outside app")
  endif()
  set(${result} "${error}" PARENT_SCOPE)
endfunction()

# Positive and negative examples keep an accidentally ineffective rule from passing silently.
function(expect source line allowed)
  check_line("${source}" "${line}" error)
  if((allowed AND error) OR (NOT allowed AND NOT error))
    message(FATAL_ERROR "Boundary rule self-test failed: ${source}: ${line}: ${error}")
  endif()
endfunction()
expect(app/cli.cpp "#include <CLI/CLI.hpp>" TRUE)
expect(audio/reader.cpp "#include <libavformat/avformat.h>" TRUE)
expect(inference/runtime.cpp "#include \"ggml-backend.h\"" TRUE)
expect(models/download.cpp "#include <curl/curl.h>" TRUE)
expect(transcript/metadata.cpp "#include \"inference/options.hpp\"" TRUE)
expect(transcript/render/render.cpp "#include \"transcript/render/render.hpp\"" TRUE)
expect(transcript/render/json.cpp "#include \"transcript/render/detail/formatters.hpp\"" TRUE)
expect(transcript/checkpoint/storage.cpp "#include \"transcript/checkpoint/detail/privacy.hpp\"" TRUE)
expect(transcript/checkpoint/detail/privacy.hpp "#include \"support/permissions.hpp\"" TRUE)
expect(transcript/publication.cpp "#include \"transcript/render/render.hpp\"" TRUE)
expect(transcript/publication.cpp "#include \"transcript/checkpoint/journal.hpp\"" TRUE)
expect(models/models.cpp "#include \"app/options.hpp\"" FALSE)
expect(support/test.cpp "#include <CLI/CLI.hpp>" FALSE)
expect(transcript/pipeline.cpp "#include <libavcodec/avcodec.h>" FALSE)
expect(audio/reader.hpp "#include <libavformat/avformat.h>" FALSE)
expect(audio/reader.cpp "#include \"audio/detail/logging.hpp\"" TRUE)
expect(app/doctor.cpp "#include \"audio/detail/logging.hpp\"" FALSE)
expect(audio/reader.hpp "#include \"audio/detail/error.hpp\"" FALSE)
expect(inference/whisper.cpp "#include \"transcript/boundaries.hpp\"" TRUE)
expect(inference/whisper.cpp "#include \"transcript/pipeline.hpp\"" FALSE)
expect(transcript/boundaries.cpp "#include \"transcript/types.hpp\"" TRUE)
expect(transcript/boundaries.cpp "#include \"transcript/checkpoint/journal.hpp\"" FALSE)
expect(transcript/boundaries.hpp "#include \"support/files.hpp\"" FALSE)
expect(models/models.cpp "#include \"whisper.h\"" FALSE)
expect(inference/whisper.hpp "#include \"whisper.h\"" FALSE)
expect(app/main.cpp "#include <curl/curl.h>" FALSE)
expect(transcript/render/json.cpp "#include \"transcript/metadata.hpp\"" FALSE)
expect(transcript/render/text.cpp "#include \"support/atomic.hpp\"" FALSE)
expect(transcript/render/render.hpp "#include \"transcript/publication.hpp\"" FALSE)
expect(transcript/render/render.cpp "#include \"transcript/checkpoint/journal.hpp\"" FALSE)
expect(transcript/checkpoint/journal.cpp "#include \"transcript/render/render.hpp\"" FALSE)
expect(transcript/checkpoint/journal.hpp "#include \"transcript/checkpoint/detail/privacy.hpp\"" FALSE)
expect(app/transcribe.cpp "#include \"transcript/render/detail/formatters.hpp\"" FALSE)
expect(transcript/publication.cpp "#include \"transcript/checkpoint/detail/storage.hpp\"" FALSE)
expect(models/models.hpp "#include \"models/download.hpp\"" FALSE)
expect(models/types.hpp "#include \"platform/file.hpp\"" FALSE)
expect(transcript/checkpoint/journal.hpp "struct CliOptions;" FALSE)
expect(platform/file-win32.cpp "#include \"platform/win32/handles.hpp\"" TRUE)
expect(platform/win32/status.cpp "#include \"platform/win32/security.hpp\"" TRUE)
expect(platform/win32/security.hpp "#include \"platform/win32/handles.hpp\"" TRUE)
expect(platform/file.hpp "#include \"platform/win32/handles.hpp\"" FALSE)
expect(support/atomic.cpp "#include \"platform/win32/handles.hpp\"" FALSE)
expect(support/files.cpp "#include \"support/io.hpp\"" FALSE)

file(GLOB_RECURSE sources RELATIVE "${WT_SOURCE}/src" "${WT_SOURCE}/src/*.cpp" "${WT_SOURCE}/src/*.hpp")
list(LENGTH sources count)
if(count LESS 10)
  message(FATAL_ERROR "Expected project sources under ${WT_SOURCE}/src")
endif()
set(violations)
foreach(source IN LISTS sources)
  file(STRINGS "${WT_SOURCE}/src/${source}" lines REGEX "include|CliOptions")
  foreach(line IN LISTS lines)
    check_line("${source}" "${line}" error)
    if(error)
      list(APPEND violations "${source}: ${error}: ${line}")
    endif()
  endforeach()
endforeach()
if(violations)
  list(JOIN violations "\n  " violations)
  message(FATAL_ERROR "Module boundary violations:\n  ${violations}")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/test-support-boundary.cmake")
