# Keep test infrastructure independent of domain fixtures and their application settings.
function(check_test_include source header result)
  set(error "")
  if(header STREQUAL "support/fixtures.hpp")
    set(error "retired fixture umbrella instead of a domain-specific fixture")
  elseif(source STREQUAL "support/test.hpp" AND
      header MATCHES "^(app|audio|inference|models|platform|support|transcript)/" AND
      NOT header STREQUAL "support/fs.hpp")
    set(error "assertion/runner API leaks fixture or platform helpers")
  elseif(source MATCHES "^support/platform/" AND
      header MATCHES "^(app|audio|inference|models|transcript)/|^support/fixtures/")
    set(error "native test helper depends on application/domain fixtures")
  endif()
  set(${result} "${error}" PARENT_SCOPE)
endfunction()
function(expect_test_include source header allowed)
  check_test_include("${source}" "${header}" error)
  if((allowed AND error) OR (NOT allowed AND NOT error))
    message(FATAL_ERROR "Test-support rule self-test failed: ${source}: ${header}: ${error}")
  endif()
endfunction()
expect_test_include(support/test.hpp support/fs.hpp TRUE)
expect_test_include(support/test.hpp support/scoped.hpp FALSE)
expect_test_include(support/test.hpp support/platform/memory.hpp FALSE)
expect_test_include(support/test.cpp support/fixtures/directory.hpp TRUE)
expect_test_include(support/platform/process.cpp support/test.hpp TRUE)
expect_test_include(support/platform/process.cpp app/options.hpp FALSE)
expect_test_include(support/platform/process.cpp support/fixtures/transcript.hpp FALSE)
expect_test_include(unit/models/model-cache.cpp support/fixtures.hpp FALSE)

file(GLOB_RECURSE test_sources RELATIVE "${WT_SOURCE}/tests" "${WT_SOURCE}/tests/*.cpp" "${WT_SOURCE}/tests/*.hpp")
foreach(source IN LISTS test_sources)
  file(STRINGS "${WT_SOURCE}/tests/${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*\"")
  foreach(line IN LISTS includes)
    if(line MATCHES "include[ \t]*\"([^\"]+)\"")
      check_test_include("${source}" "${CMAKE_MATCH_1}" error)
      if(error)
        message(FATAL_ERROR "Test-support boundary violation: ${source}: ${error}: ${line}")
      endif()
    endif()
  endforeach()
endforeach()
