# Stage the common source archives and notices from an existing build, without Git or downloads.
cmake_minimum_required(VERSION 3.22)
foreach(input IN ITEMS WT_SOURCE_DIR WT_BUILD_DIR WT_BUNDLE_DIR)
    if(NOT DEFINED ${input} OR "${${input}}" STREQUAL "")
        message(FATAL_ERROR "Required input: ${input}")
    endif()
    get_filename_component(${input} "${${input}}" ABSOLUTE)
endforeach()

file(STRINGS "${WT_BUILD_DIR}/generated/package.env" metadata)
foreach(line IN LISTS metadata)
    if(NOT line MATCHES "^([A-Z_0-9]+)=([^\r\n]*)$")
        message(FATAL_ERROR "Invalid package metadata: ${line}")
    endif()
    set(key "${CMAKE_MATCH_1}")
    if(DEFINED metadata_${key})
        message(FATAL_ERROR "Duplicate package metadata: ${key}")
    endif()
    set(metadata_${key} "${CMAKE_MATCH_2}")
endforeach()
foreach(key IN ITEMS WT_PACKAGE_VERSION WT_WHISPER_REVISION WT_CLI11_VERSION WT_JSON_VERSION)
    if(NOT DEFINED metadata_${key} OR NOT metadata_${key} MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$")
        message(FATAL_ERROR "Missing or unsafe package metadata: ${key}")
    endif()
endforeach()

# Keep this allowlist independent of the Git-based release/source verifiers.
set(project_inputs CMakeLists.txt CMakePresets.json vcpkg.json .gitattributes cmake src tests packaging LICENSE)
foreach(path IN LISTS project_inputs)
    if(NOT EXISTS "${WT_SOURCE_DIR}/${path}")
        message(FATAL_ERROR "Missing project source: ${path}")
    endif()
endforeach()
foreach(path IN ITEMS whisper-src/LICENSE cli11-src/LICENSE nlohmann_json-src/LICENSE.MIT)
    if(NOT EXISTS "${WT_BUILD_DIR}/_deps/${path}")
        message(FATAL_ERROR "Missing dependency notice: ${path}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${WT_BUNDLE_DIR}/sources" "${WT_BUNDLE_DIR}/licenses" "${WT_BUNDLE_DIR}/share")
# Avoid AppleDouble entries on macOS; CMake's tar also keeps dotfiles and LF source bytes on Windows.
set(ENV{COPYFILE_DISABLE} 1)
function(archive_sources directory name)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${WT_BUNDLE_DIR}/sources/${name}.tar.gz" -- ${ARGN}
        WORKING_DIRECTORY "${directory}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()
function(dependency directory name notice license)
    archive_sources("${WT_BUILD_DIR}/_deps/${directory}-src" "${name}" .)
    configure_file("${WT_BUILD_DIR}/_deps/${directory}-src/${notice}"
        "${WT_BUNDLE_DIR}/licenses/${license}.txt" COPYONLY)
endfunction()
dependency(whisper "whisper.cpp-${metadata_WT_WHISPER_REVISION}" LICENSE whisper.cpp-MIT)
dependency(cli11 "CLI11-${metadata_WT_CLI11_VERSION}" LICENSE CLI11-BSD)
dependency(nlohmann_json "nlohmann-json-${metadata_WT_JSON_VERSION}" LICENSE.MIT nlohmann-json-MIT)
archive_sources("${WT_SOURCE_DIR}" "whisper-transcribator-${metadata_WT_PACKAGE_VERSION}" ${project_inputs})
configure_file("${WT_SOURCE_DIR}/LICENSE" "${WT_BUNDLE_DIR}/licenses/whisper-transcribator-MIT.txt" COPYONLY)

if(DEFINED WT_VULKAN_SDK AND NOT WT_VULKAN_SDK STREQUAL "")
    # Windows and Linux SDKs differ in layout and do not share a root LICENSE.txt.
    # Ship the licenses of the actual header components, not a generic SDK notice.
    set(headers "${WT_VULKAN_SDK}/include")
    if(NOT IS_DIRECTORY "${headers}")
        set(headers "${WT_VULKAN_SDK}/Include")
    endif()
    foreach(header IN ITEMS vulkan/vulkan.hpp vk_video/vulkan_video_codec_h264std.h spirv/unified1/spirv.hpp)
        if(NOT EXISTS "${headers}/${header}")
            message(FATAL_ERROR "Missing Vulkan SDK header: ${header}")
        endif()
    endforeach()
    foreach(notice IN ITEMS vulkan-headers-notice.txt licenses/Apache-2.0.txt vulkan-sdk.json)
        if(NOT EXISTS "${WT_SOURCE_DIR}/packaging/${notice}")
            message(FATAL_ERROR "Missing Vulkan provenance: ${notice}")
        endif()
    endforeach()
    archive_sources("${headers}" vulkan-sdk-headers vulkan vk_video spirv)
    configure_file("${WT_SOURCE_DIR}/packaging/vulkan-headers-notice.txt"
        "${WT_BUNDLE_DIR}/licenses/Vulkan-headers.txt" COPYONLY)
    configure_file("${WT_SOURCE_DIR}/packaging/licenses/Apache-2.0.txt"
        "${WT_BUNDLE_DIR}/licenses/Apache-2.0.txt" COPYONLY)
    configure_file("${WT_SOURCE_DIR}/packaging/vulkan-sdk.json"
        "${WT_BUNDLE_DIR}/share/vulkan-sdk.json" COPYONLY)
endif()
