find_program(WT_CLANG_CL clang-cl HINTS "$ENV{ProgramFiles}/LLVM/bin" REQUIRED)
set(CMAKE_C_COMPILER "${WT_CLANG_CL}")
set(CMAKE_CXX_COMPILER "${WT_CLANG_CL}")
set(CMAKE_C_COMPILER_TARGET aarch64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET aarch64-pc-windows-msvc)
file(TO_CMAKE_PATH "$ENV{VCToolsInstallDir}/bin/Host$ENV{VSCMD_ARG_HOST_ARCH}/arm64/link.exe" CMAKE_LINKER)
file(TO_CMAKE_PATH "$ENV{WindowsSdkVerBinPath}/$ENV{VSCMD_ARG_HOST_ARCH}/mt.exe" CMAKE_MT)
include("${VCPKG_ROOT}/scripts/toolchains/windows.cmake")
