# Applied by FetchContent to the pinned whisper.cpp sources; a FETCHCONTENT_SOURCE_DIR_WHISPER
# override is used unpatched. whisper_full() creates its VAD context with the default of four
# threads instead of whisper_full_params.n_threads. Without OpenMP (macOS, Linux aarch64
# archives), ggml's spinning thread pool then made VAD more than 40 times slower on fewer than
# four free cores.
set(file "${WT_WHISPER_SOURCE}/src/whisper.cpp")
file(READ "${file}" text)
set(original "${text}")
set(anchor "        struct whisper_vad_context_params vad_ctx_params = whisper_vad_default_context_params();\n")
set(line "        vad_ctx_params.n_threads = params.n_threads;\n")
string(FIND "${text}" "${anchor}${line}" patched)
if(patched EQUAL -1)
  string(FIND "${text}" "${anchor}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "whisper.cpp VAD context setup changed; review cmake/patch-whisper.cmake")
  endif()
  string(REPLACE "${anchor}" "${anchor}${line}" text "${text}")
endif()
# Explicit GPU selection must not silently initialize a CPU-only inference state.
set(anchor "    ggml_backend_t backend_gpu = whisper_backend_init_gpu(params);\n")
set(line "    if (params.use_gpu && !backend_gpu) {\n        return {};\n    }\n")
string(FIND "${text}" "${anchor}${line}" patched)
if(patched EQUAL -1)
  string(FIND "${text}" "${anchor}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "whisper.cpp GPU initialization changed; review cmake/patch-whisper.cmake")
  endif()
  string(REPLACE "${anchor}" "${anchor}${line}" text "${text}")
endif()
# The empty-backend error path frees state->batch before whisper_batch_init() ran.
# Value-initialize the state so early cleanup never frees indeterminate pointers.
set(anchor "whisper_state * state = new whisper_state;")
set(line "whisper_state * state = new whisper_state{};")
string(FIND "${text}" "${line}" patched)
if(patched EQUAL -1)
  string(FIND "${text}" "${anchor}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "whisper.cpp state allocation changed; review cmake/patch-whisper.cmake")
  endif()
  string(REPLACE "${anchor}" "${line}" text "${text}")
endif()
if(NOT text STREQUAL original)
  file(WRITE "${file}" "${text}")
endif()

# The pinned ggml already probes Windows ARM features with IsProcessorFeaturePresent,
# but its multi-variant build has no Windows branch (also absent in ggml 353b63b4).
# Keep feature probes baseline-safe and use NEON variants without SVE/SME requirements.
set(file "${WT_WHISPER_SOURCE}/ggml/src/CMakeLists.txt")
file(READ "${file}" text)
set(anchor "        elseif (CMAKE_SYSTEM_NAME MATCHES \"Android\")\n            # Android-specific backends")
set(variants [=[        elseif (WIN32)
            ggml_add_cpu_backend_variant(armv8.0_1)
            ggml_add_cpu_backend_variant(armv8.2_1    DOTPROD)
            ggml_add_cpu_backend_variant(armv8.2_2    DOTPROD FP16_VECTOR_ARITHMETIC)
            ggml_add_cpu_backend_variant(armv8.6_1    DOTPROD FP16_VECTOR_ARITHMETIC MATMUL_INT8 NOSVE)
]=])
string(FIND "${text}" "${variants}${anchor}" patched)
if(patched EQUAL -1)
  string(FIND "${text}" "${anchor}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "ggml ARM variants changed; review cmake/patch-whisper.cmake")
  endif()
  string(REPLACE "${anchor}" "${variants}${anchor}" text "${text}")
  file(WRITE "${file}" "${text}")
endif()
